// Generated by CoffeeScript 1.3.3
/*global module, require
*/

module.exports = function(grunt) {
  var os, path, _;
  os = require('os');
  path = require('path');
  _ = grunt.utils._;
  return grunt.registerMultiTask('coffee', 'Compile CoffeeScript to JavaScript', function() {
    var args, bare, child, cmd, dest, done, isWindows, src, _ref;
    done = this.async();
    src = this.file.src;
    dest = this.file.dest;
    bare = (_ref = this.data.bare) != null ? _ref : false;
    isWindows = !!process.platform.match(/^win/);
    cmd = isWindows ? 'cmd' : 'node';
    args = [];
    if (isWindows) {
      args.push('/c');
    }
    args.push(path.normalize('./node_modules/.bin/coffee'));
    args.push('--compile');
    if (bare) {
      args.push('--bare');
    }
    args.push('--output');
    args.push(path.normalize(dest));
    args.push(path.normalize(src));
    child = grunt.utils.spawn({
      cmd: cmd,
      args: args
    }, function(err) {
      if (err) {
        grunt.log.error(err);
      } else {
        grunt.log.write('coffee success');
      }
      return done(true);
    });
    child.stdout.on('data', function(buffer) {
      return grunt.log.writeln(_.rtrim(buffer));
    });
    return child.stderr.on('data', function(buffer) {
      return grunt.log.writeln(_.rtrim(buffer));
    });
  });
};
