// Generated by CoffeeScript 1.3.3
/*global module, require
*/

module.exports = function(grunt) {
  var coffeeLint;
  coffeeLint = require('coffeelint');
  grunt.registerHelper('hustler coffeeLint', function(data) {
    var dest, groups, normalized, src, _results;
    normalized = grunt.helper('hustler normalizeFiles', data);
    groups = normalized.groups;
    _results = [];
    for (dest in groups) {
      src = groups[dest];
      _results.push(src.forEach(function(source) {
        var contents, errors;
        contents = grunt.file.read(source);
        errors = coffeeLint.lint(contents, data.data);
        if (!errors.length) {
          return grunt.verbose.ok(source);
        }
        grunt.log.header(source);
        return errors.forEach(function(error) {
          return grunt.log.error("#" + error.lineNumber + ": " + error.message + " (" + error.context + ")");
        });
      }));
    }
    return _results;
  });
  return grunt.registerMultiTask('coffeeLint', 'Lints CoffeeScript files', function() {
    return grunt.helper('hustler coffeeLint', this);
  });
};
