// Generated by CoffeeScript 1.4.0

/*global module, require
*/


(function() {

  module.exports = function(grunt) {
    var coffee;
    coffee = require('coffee-script');
    grunt.registerHelper('hustler coffee', function(config) {
      var bare, compiled, contents, dest, destination, groups, normalized, separator, sourceContents, src, _ref, _results;
      normalized = grunt.helper('hustler normalizeFiles', config);
      groups = normalized.groups;
      bare = (_ref = config.data.bare) != null ? _ref : false;
      _results = [];
      for (dest in groups) {
        src = groups[dest];
        sourceContents = [];
        src.forEach(function(source) {
          var contents;
          contents = grunt.file.read(source);
          return sourceContents.push(contents);
        });
        separator = grunt.utils.linefeed;
        contents = sourceContents.join(grunt.utils.normalizelf(separator));
        destination = dest.replace('.coffee', '.js');
        try {
          compiled = coffee.compile(contents, {
            bare: bare,
            filename: src
          });
          grunt.file.write(destination, compiled);
          _results.push(grunt.verbose.ok("" + src + " -> " + destination));
        } catch (e) {
          _results.push(grunt.fail.warn("" + src + " -> " + destination));
        }
      }
      return _results;
    });
    return grunt.registerMultiTask('coffee', 'Compile CoffeeScript to JavaScript', function() {
      return grunt.helper('hustler coffee', this);
    });
  };

}).call(this);
