// Generated by CoffeeScript 1.3.3
/*global module, require
*/

module.exports = function(grunt) {
  var coffeeScript;
  coffeeScript = require('coffee-script');
  return grunt.registerMultiTask('coffee', 'Compile CoffeeScript to JavaScript', function() {
    var args, bare, cmd, dest, done, src, _ref;
    done = this.async();
    src = this.file.src;
    dest = this.file.dest;
    bare = (_ref = this.data.bare) != null ? _ref : false;
    cmd = 'node';
    args = ['node_modules/.bin/coffee', '--compile', bare ? '--bare' : void 0, '--output', dest, src];
    return grunt.utils.spawn({
      cmd: cmd,
      args: args
    }, function(err) {
      if (err) {
        grunt.log.error(err);
      } else {
        grunt.log.write('coffee success');
      }
      return done(true);
    });
  });
};
