// Generated by CoffeeScript 1.3.3
/*global module, require
*/

module.exports = function(grunt) {
  var fs, isDirectory, wrench;
  fs = require('fs');
  wrench = require('wrench');
  isDirectory = function(path) {
    var isADirectory, stats;
    stats = fs.lstatSync(path);
    isADirectory = stats.isDirectory();
    return isADirectory;
  };
  return grunt.registerMultiTask('copy', 'Copies a directory', function() {
    var contents, dest, isSrcADirectory, src;
    src = this.file.src;
    dest = this.file.dest;
    if (!fs.existsSync(src)) {
      return;
    }
    isSrcADirectory = isDirectory(src);
    if (isSrcADirectory) {
      wrench.mkdirSyncRecursive(dest, 0x1ff);
      return wrench.copyDirSyncRecursive(src, dest);
    } else {
      contents = grunt.file.read(src);
      return grunt.file.write(dest, contents);
    }
  });
};
