// Generated by CoffeeScript 1.3.3
/*global module, require
*/

module.exports = function(grunt) {
  var fs;
  fs = require('fs');
  grunt.registerHelper('hustler copy', function(data) {
    var contents, dest, groups, normalized, src, srcCount, _results;
    normalized = grunt.helper('hustler normalizeFiles', data);
    groups = normalized.groups;
    _results = [];
    for (dest in groups) {
      src = groups[dest];
      srcCount = src.length;
      if (srcCount > 1) {
        contents = grunt.helper('concat', src);
      } else {
        contents = fs.readFileSync(src[0]);
      }
      grunt.file.write(dest, contents);
      _results.push(grunt.verbose.ok("" + src + " -> " + dest));
    }
    return _results;
  });
  return grunt.registerMultiTask('copy', 'Copies files and directories', function() {
    return grunt.helper('hustler copy', this);
  });
};
