// Generated by CoffeeScript 1.3.3
/*global module, require
*/

module.exports = function(grunt) {
  var deleteFileObjects, fs, rimraf;
  fs = require('fs');
  rimraf = require('rimraf');
  deleteFileObjects = function(command, fileObjects) {
    return fileObjects.forEach(function(fileObject) {
      command(fileObject);
      return grunt.log.ok(fileObject);
    });
  };
  return grunt.registerMultiTask('delete', 'Deletes files and directories', function() {
    var directories, files, src;
    src = this.file.src;
    files = grunt.file.expandFiles(src);
    directories = grunt.file.expandDirs(src);
    deleteFileObjects(fs.unlinkSync, files);
    return deleteFileObjects(rimraf.sync, directories);
  });
};
