// Generated by CoffeeScript 1.3.3
/*global module, require
*/

module.exports = function(grunt) {
  var deleteDirectory, deleteFile, deleteFileObject, fs, rimraf;
  fs = require('fs');
  rimraf = require('rimraf');
  deleteFileObject = function(command, fileObject) {
    command(fileObject);
    return grunt.log.ok(fileObject);
  };
  deleteFile = function(file) {
    return deleteFileObject(fs.unlinkSync, file);
  };
  deleteDirectory = function(directory) {
    return deleteFileObject(rimraf.sync, directory);
  };
  grunt.registerHelper('hustler delete', function(data) {
    var dest, dirs, groups, normalized, src, _results;
    normalized = grunt.helper('hustler normalizeFiles', data);
    dirs = normalized.dirs;
    groups = normalized.groups;
    for (dest in dirs) {
      src = dirs[dest];
      deleteFileObject(deleteDirectory, dest);
    }
    _results = [];
    for (dest in groups) {
      src = groups[dest];
      _results.push(src.forEach(function(source) {
        var exists;
        exists = fs.existsSync(source);
        if (exists) {
          return deleteFileObject(deleteFile, source);
        }
      }));
    }
    return _results;
  });
  return grunt.registerMultiTask('delete', 'Deletes files and directories', function() {
    return grunt.helper('hustler delete', this);
  });
};
