// Generated by CoffeeScript 1.3.3
/*global module, require
*/

module.exports = function(grunt) {
  var wrapScript;
  wrapScript = function(contents, type, id, trim) {
    var script;
    if (trim) {
      id = id.replace(trim, '');
    }
    script = "<script type=\"" + type + "\" id=\"" + id + "\">" + contents + "</script>";
    return script;
  };
  grunt.registerHelper('hustler inlineTemplate', function(config) {
    var contents, dest, groups, normalized, separator, sourceContents, src, trim, type, _results;
    normalized = grunt.helper('hustler normalizeFiles', config);
    groups = normalized.groups;
    type = config.data.type;
    trim = config.data.trim;
    _results = [];
    for (dest in groups) {
      src = groups[dest];
      sourceContents = [];
      src.forEach(function(source) {
        var contents, script;
        contents = grunt.file.read(source);
        script = wrapScript(contents, type, source, trim);
        return sourceContents.push(script);
      });
      separator = grunt.utils.linefeed;
      contents = sourceContents.join(grunt.utils.normalizelf(separator));
      grunt.file.write(dest, contents);
      _results.push(grunt.verbose.ok("" + src + " -> " + dest));
    }
    return _results;
  });
  return grunt.registerMultiTask('inlineTemplate', 'Inlines templates', function() {
    return grunt.helper('hustler inlineTemplate', this);
  });
};
