// Generated by CoffeeScript 1.3.3
/*global module, require
*/

module.exports = function(grunt) {
  var requirejs;
  requirejs = require('requirejs');
  return grunt.registerMultiTask('requirejs', 'Runs the RequireJS Optimizer', function() {
    var config, done;
    done = this.async();
    config = this.data;
    return requirejs.optimize(config, function(buildResponse) {
      grunt.verbose.writeln(buildResponse);
      return done();
    });
  });
};
