// Generated by CoffeeScript 1.3.3
/*global module, require
*/

module.exports = function(grunt) {
  return grunt.registerMultiTask('server', 'Run a server', function() {
    var config, done, port, src, watch;
    done = this.async();
    src = this.file.src;
    config = this.data;
    port = config.port;
    watch = config.watch;
    process.env.PORT = port;
    process.argv[2] = src;
    if (watch) {
      process.argv[3] = "--watch " + watch;
    }
    return require('nodemon');
  });
};
