// Generated by CoffeeScript 1.3.3
/*global module, require
*/

module.exports = function(grunt) {
  return grunt.registerMultiTask('server', 'Run a server', function() {
    var args, cmd, config, done, port, src, target, watch;
    done = this.async();
    src = this.file.src;
    target = this.target;
    config = this.data;
    watch = config.watch;
    port = config.port;
    cmd = 'node';
    if (watch) {
      args = ['node_modules/.bin/nodemon', src, '-w', watch, port];
    } else {
      args = [src, port];
    }
    grunt.log.write("starting \"" + target + "\" web server at \"http://localhost:" + port + "\"");
    return grunt.utils.spawn({
      cmd: cmd,
      args: args
    }, function(err) {
      if (err) {
        grunt.log.error(err);
      } else {
        grunt.log.write('server success');
      }
      return done(true);
    });
  });
};
