// Generated by CoffeeScript 1.3.3
/*global module, require
*/

module.exports = function(grunt) {
  grunt.registerHelper('hustler template', function(config) {
    var compiled, contents, dest, destination, groups, normalized, separator, sourceContents, src, _results;
    normalized = grunt.helper('hustler normalizeFiles', config);
    groups = normalized.groups;
    config.data.include = grunt.file.read;
    config.data.uniqueVersion = function() {
      var uniqueVersion;
      uniqueVersion = (new Date()).getTime();
      return uniqueVersion;
    };
    _results = [];
    for (dest in groups) {
      src = groups[dest];
      sourceContents = [];
      src.forEach(function(source) {
        var contents;
        contents = grunt.file.read(source);
        return sourceContents.push(contents);
      });
      separator = grunt.utils.linefeed;
      contents = sourceContents.join(grunt.utils.normalizelf(separator));
      compiled = grunt.template.process(contents, {
        config: config.data
      });
      destination = dest.replace('.template', '.html');
      grunt.file.write(destination, compiled);
      _results.push(grunt.verbose.ok("" + src + " -> " + destination));
    }
    return _results;
  });
  return grunt.registerMultiTask('template', 'Compiles templates', function() {
    return grunt.helper('hustler template', this);
  });
};
